### ISSUE TITLE
windows 10 liquidlauncher slow move

### ISSUE THREAD

**Issue by wowfilip999** [CCBlueX/LiquidLauncher#176]
when i move liquidbounce on screen it slow lagy move liblary error?

**Comment by 1zun4** [comment]
This is a known issue with blur and Windows 10. Please consider updating to Windows 11, which seems to have addressed this issue or might also try to lower your mouse pull rate (which also causes this issue) to happen. We cannot do much about this sadly, due to the poor blur implementation on Windows.

on Windows 11: https://www.youtube.com/watch?v=jk7NZG7kwjw
on Windows 10/early 11 preview: https://www.youtube.com/watch?v=D8_ix5aaoX4

https://github.com/CCBlueX/LiquidLauncher/blob/818ba245d36fb009b53468fd14c22bd247ffcda6/src-tauri/src/app/gui.rs#L298-L315
On systems which cannot use acrylic blur (which does not have this issue), it will fall back to blur (which will lag out on high dpi mouse pull rate).

**Comment by BeeTreeOfficial** [comment]
falling back to using jar manually i guess
